# -*- python -*- vim:syntax=python:
# A simple library consisting of one source file.  Note that when Cobble says
# "library," it currently means "static library."
c_library('bar',
  sources = [ 'bar.c' ],
)
